const { test, expect } = require('@playwright/test');

/**
 * Google Homepage Launch Verification Test Suite
 * 
 * Generated by: Planner Agent → Generator Agent
 * Test Plan: docs/GOOGLE_LAUNCH_TEST_PLAN.md
 * Self-Healing: Enabled (flexible selectors, robust waits, contains-based assertions)
 * 
 * Strategies used for self-healing resilience:
 *  - Role-based and aria-label selectors (fall back to text/CSS)
 *  - domcontentloaded + networkidle wait strategy
 *  - toContain / regex assertions instead of exact match
 *  - Generous timeouts with per-step error handling
 */

test.describe('Google Homepage Launch Verification', () => {

  test('Test Case 1: [UI] Verify Google homepage launches successfully', async ({ page }) => {
    // ── Step 1: Navigate to Google ──────────────────────────────────────
    console.log('📍 Step 1: Navigating to https://www.google.com');
    await page.goto('https://www.google.com', {
      waitUntil: 'domcontentloaded',
      timeout: 30000
    });

    // ── Step 2: Wait for page to fully load ─────────────────────────────
    console.log('📍 Step 2: Waiting for page to fully load');
    try {
      await page.waitForLoadState('networkidle', { timeout: 15000 });
    } catch {
      // networkidle may not always fire on google.com; continue if domcontentloaded succeeded
      console.log('⚠️  networkidle timeout – continuing (page already loaded via domcontentloaded)');
    }

    // ── Step 3: Verify page title contains "Google" ─────────────────────
    console.log('📍 Step 3: Verifying page title contains "Google"');
    const title = await page.title();
    expect(title.toLowerCase()).toContain('google');
    console.log(`✓ Page title: "${title}"`);

    // ── Step 4: Verify URL contains "google.com" ────────────────────────
    console.log('📍 Step 4: Verifying URL contains "google.com"');
    const url = page.url();
    expect(url).toContain('google.com');
    console.log(`✓ Page URL: ${url}`);

    // ── Step 5: Verify Google logo / branding is visible ────────────────
    console.log('📍 Step 5: Verifying Google logo / branding is visible');
    // Self-healing: try multiple selector strategies
    const logoSelectors = [
      'img[alt="Google"]',                          // standard alt text
      'img[src*="googlelogo"]',                     // src contains googlelogo
      'img[id="hplogo"]',                           // classic homepage logo id
      '[aria-label="Google"]',                      // aria-label
      'img[alt*="oogle"]',                          // partial alt match
      '#logo img',                                  // logo container
      'img[class*="logo"]',                         // class contains logo
    ];

    let logoFound = false;
    for (const selector of logoSelectors) {
      try {
        const logo = page.locator(selector).first();
        await expect(logo).toBeVisible({ timeout: 5000 });
        logoFound = true;
        console.log(`✓ Google logo found with selector: ${selector}`);
        break;
      } catch {
        // try next selector
      }
    }

    if (!logoFound) {
      // Final fallback: check for any img or svg on the page that's likely a logo
      const anyBranding = page.locator('img').first();
      await expect(anyBranding).toBeVisible({ timeout: 5000 });
      console.log('✓ Google branding detected (fallback image selector)');
    }

    // ── Step 6: Verify search input is visible ──────────────────────────
    console.log('📍 Step 6: Verifying search input field is visible');
    // Self-healing: try multiple search input selectors
    const searchInputSelectors = [
      'textarea[name="q"]',                         // Google recently uses textarea
      'input[name="q"]',                            // classic search input
      '[aria-label="Search"]',                      // aria-label based
      'textarea[title="Search"]',                   // textarea with title
      'input[title="Search"]',                      // input with title
      '[role="combobox"]',                           // role-based
    ];

    let searchInput = null;
    for (const selector of searchInputSelectors) {
      try {
        const input = page.locator(selector).first();
        await expect(input).toBeVisible({ timeout: 5000 });
        searchInput = input;
        console.log(`✓ Search input found with selector: ${selector}`);
        break;
      } catch {
        // try next selector
      }
    }

    if (!searchInput) {
      // Aggressive fallback
      searchInput = page.locator('textarea, input[type="text"]').first();
      await expect(searchInput).toBeVisible({ timeout: 5000 });
      console.log('✓ Search input found (fallback selector)');
    }

    // ── Step 7: Verify search button is visible ─────────────────────────
    console.log('📍 Step 7: Verifying search button is visible');
    // Self-healing: try multiple button selectors
    const buttonSelectors = [
      'input[name="btnK"]',                         // "Google Search" submit button
      'input[value="Google Search"]',               // by value text
      'button:has-text("Google Search")',            // button with text
      '[aria-label="Google Search"]',               // aria-label
      'input[type="submit"]',                       // any submit input
      'button[type="submit"]',                      // any submit button
      'input[name="btnI"]',                         // "I\'m Feeling Lucky" as fallback
    ];

    let buttonFound = false;
    for (const selector of buttonSelectors) {
      try {
        const button = page.locator(selector).first();
        await expect(button).toBeVisible({ timeout: 5000 });
        buttonFound = true;
        console.log(`✓ Search button found with selector: ${selector}`);
        break;
      } catch {
        // try next selector
      }
    }

    if (!buttonFound) {
      // If buttons are hidden (Google sometimes hides them until focused), 
      // verify at least one input[type="submit"] or button exists in the DOM
      const anyButton = page.locator('input[type="submit"], button').first();
      await expect(anyButton).toBeAttached({ timeout: 5000 });
      console.log('✓ Search button exists in DOM (may be hidden until interaction)');
    }

    console.log('✅ All verifications passed – Google homepage launched successfully!');
  });

  test('Test Case 2: [UI] Verify Google search input is functional', async ({ page }) => {
    // ── Step 1: Navigate to Google ──────────────────────────────────────
    console.log('📍 Step 1: Navigating to https://www.google.com');
    await page.goto('https://www.google.com', {
      waitUntil: 'domcontentloaded',
      timeout: 30000
    });

    try {
      await page.waitForLoadState('networkidle', { timeout: 15000 });
    } catch {
      console.log('⚠️  networkidle timeout – continuing');
    }

    // ── Step 2: Find and click the search input ─────────────────────────
    console.log('📍 Step 2: Finding and clicking the search input');
    const searchSelectors = [
      'textarea[name="q"]',
      'input[name="q"]',
      '[aria-label="Search"]',
      'textarea[title="Search"]',
      'input[title="Search"]',
      '[role="combobox"]',
    ];

    let searchInput = null;
    for (const selector of searchSelectors) {
      try {
        const input = page.locator(selector).first();
        await expect(input).toBeVisible({ timeout: 5000 });
        searchInput = input;
        console.log(`✓ Search input found: ${selector}`);
        break;
      } catch {
        // try next
      }
    }

    if (!searchInput) {
      searchInput = page.locator('textarea, input[type="text"]').first();
      await expect(searchInput).toBeVisible({ timeout: 5000 });
      console.log('✓ Search input found (fallback)');
    }

    await searchInput.click();

    // ── Step 3: Type text into search ───────────────────────────────────
    console.log('📍 Step 3: Typing "Playwright automation" into search');
    await searchInput.fill('Playwright automation');

    // ── Step 4: Verify typed text ───────────────────────────────────────
    console.log('📍 Step 4: Verifying typed text appears in search input');
    const inputValue = await searchInput.inputValue();
    expect(inputValue).toContain('Playwright automation');
    console.log(`✓ Search input value: "${inputValue}"`);

    console.log('✅ Search input is functional – text accepted successfully!');
  });

});
