import { test, expect } from '@playwright/test';

/**
 * SauceDemo - Login  Add to Cart  Checkout  Validation
 * Generated from playwright-cli session on https://www.saucedemo.com
 *
 * playwright-cli commands used:
 *   npx playwright-cli open https://www.saucedemo.com
 *   npx playwright-cli fill e11 "standard_user"
 *   npx playwright-cli fill e13 "secret_sauce"
 *   npx playwright-cli click e15
 *   npx playwright-cli click e54   (Add to cart - Backpack)
 *   npx playwright-cli click e66   (Add to cart - Bike Light)
 *   npx playwright-cli goto https://www.saucedemo.com/cart.html
 *   npx playwright-cli click e53   (Checkout)
 *   npx playwright-cli fill e82 "John"
 *   npx playwright-cli fill e84 "Doe"
 *   npx playwright-cli fill e86 "12345"
 *   npx playwright-cli click e91   (Continue)
 *   npx playwright-cli click e154  (Finish)
 */

test.describe('SauceDemo - Login  Add to Cart  Checkout  Validation', () => {

  //  STEP 1: LOGIN 

  test('1 - Successful login with standard_user', async ({ page }) => {
    await page.goto('https://www.saucedemo.com');

    // Generated by: npx playwright-cli fill e11 "standard_user"
    await page.locator('[data-test="username"]').fill('standard_user');

    // Generated by: npx playwright-cli fill e13 "secret_sauce"
    await page.locator('[data-test="password"]').fill('secret_sauce');

    // Generated by: npx playwright-cli click e15
    await page.locator('[data-test="login-button"]').click();

    //  Assertions
    await expect(page).toHaveURL(/.*inventory\.html/);
    await expect(page).toHaveTitle('Swag Labs');
    await expect(page.locator('[data-test="inventory-list"]')).toBeVisible();
  });

  //  STEP 2: ADD TO CART 

  test('2 - Add Backpack and Bike Light to cart', async ({ page }) => {
    await page.goto('https://www.saucedemo.com');
    await page.locator('[data-test="username"]').fill('standard_user');
    await page.locator('[data-test="password"]').fill('secret_sauce');
    await page.locator('[data-test="login-button"]').click();

    // Generated by: npx playwright-cli click e54
    await page.locator('[data-test="add-to-cart-sauce-labs-backpack"]').click();

    // Generated by: npx playwright-cli click e66
    await page.locator('[data-test="add-to-cart-sauce-labs-bike-light"]').click();

    //  Assertions
    await expect(page.locator('[data-test="shopping-cart-badge"]')).toHaveText('2');
    await expect(page.locator('[data-test="remove-sauce-labs-backpack"]')).toBeVisible();
    await expect(page.locator('[data-test="remove-sauce-labs-bike-light"]')).toBeVisible();
  });

  //  STEP 3: CART VALIDATION 

  test('3 - Cart contains correct items', async ({ page }) => {
    await page.goto('https://www.saucedemo.com');
    await page.locator('[data-test="username"]').fill('standard_user');
    await page.locator('[data-test="password"]').fill('secret_sauce');
    await page.locator('[data-test="login-button"]').click();
    await page.locator('[data-test="add-to-cart-sauce-labs-backpack"]').click();
    await page.locator('[data-test="add-to-cart-sauce-labs-bike-light"]').click();

    // Generated by: npx playwright-cli goto https://www.saucedemo.com/cart.html
    await page.goto('https://www.saucedemo.com/cart.html');

    //  Assertions
    await expect(page.getByText('Your Cart')).toBeVisible();
    await expect(page.locator('[data-test="inventory-item-name"]').getByText('Sauce Labs Backpack')).toBeVisible();
    await expect(page.locator('[data-test="inventory-item-name"]').getByText('Sauce Labs Bike Light')).toBeVisible();
    await expect(page.getByText('$29.99')).toBeVisible();
    await expect(page.getByText('$9.99')).toBeVisible();
  });

  //  STEP 4: FULL CHECKOUT FLOW 

  test('4 - Complete checkout: Login  Cart  Checkout  Confirmation', async ({ page }) => {
    // LOGIN
    await page.goto('https://www.saucedemo.com');
    await page.locator('[data-test="username"]').fill('standard_user');
    await page.locator('[data-test="password"]').fill('secret_sauce');
    await page.locator('[data-test="login-button"]').click();
    await expect(page).toHaveURL(/.*inventory\.html/);

    // ADD TO CART
    await page.locator('[data-test="add-to-cart-sauce-labs-backpack"]').click();
    await page.locator('[data-test="add-to-cart-sauce-labs-bike-light"]').click();
    await expect(page.locator('[data-test="shopping-cart-badge"]')).toHaveText('2');

    // NAVIGATE TO CART
    await page.locator('[data-test="shopping-cart-link"]').click();
    await expect(page).toHaveURL(/.*cart\.html/);

    // Generated by: npx playwright-cli click e53
    await page.locator('[data-test="checkout"]').click();
    await expect(page).toHaveURL(/.*checkout-step-one\.html/);

    // CHECKOUT STEP 1 - CUSTOMER INFO
    // Generated by: npx playwright-cli fill e82 "John"
    await page.locator('[data-test="firstName"]').fill('John');

    // Generated by: npx playwright-cli fill e84 "Doe"
    await page.locator('[data-test="lastName"]').fill('Doe');

    // Generated by: npx playwright-cli fill e86 "12345"
    await page.locator('[data-test="postalCode"]').fill('12345');

    // Generated by: npx playwright-cli click e91
    await page.locator('[data-test="continue"]').click();
    await expect(page).toHaveURL(/.*checkout-step-two\.html/);

    // CHECKOUT STEP 2 - ORDER OVERVIEW VALIDATION
    // Verified with: npx playwright-cli eval "document.querySelector('[data-test=subtotal-label]').textContent..."
    await expect(page.locator('[data-test="subtotal-label"]')).toHaveText('Item total: $39.98');
    await expect(page.locator('[data-test="tax-label"]')).toHaveText('Tax: $3.20');
    await expect(page.locator('[data-test="total-label"]')).toHaveText('Total: $43.18');
    await expect(page.getByText('SauceCard #31337')).toBeVisible();
    await expect(page.getByText('Free Pony Express Delivery!')).toBeVisible();

    // Generated by: npx playwright-cli click e154
    await page.locator('[data-test="finish"]').click();

    // ORDER CONFIRMATION VALIDATION
    // Verified with: npx playwright-cli eval "document.querySelector('h2.complete-header').textContent"
    await expect(page).toHaveURL(/.*checkout-complete\.html/);
    await expect(page.getByText('Thank you for your order!')).toBeVisible();
    await expect(page.getByText('Checkout: Complete!')).toBeVisible();
    await expect(page.locator('[data-test="back-to-products"]')).toBeVisible();
  });

});
