// === FILE: src/tests/application/workday-finance-regression.spec.js ===
/**
 * Workday Finance Regression Suite — Capital One AAVA Demo
 *
 * Use Cases demonstrated:
 *   UC1 — AI-generated functional test cases (each test corresponds to a TestRail case)
 *   UC2 — Playwright automation of the generated test cases
 *
 * TestRail traceability:
 *   Each [Cxxx] prefix is auto-generated by push-to-testrail.js and maps to a
 *   TestRail case in Project 7 / Suite 11 / Section 50.
 *
 * Configuration:
 *   Set WORKDAY_BASE_URL, WORKDAY_USERNAME, WORKDAY_PASSWORD in .env
 *   Auth storage state is saved by globalSetup to playwright/.auth/workday-storageState.json
 *
 * Run:
 *   npx playwright test src/tests/application/workday-finance-regression.spec.js \
 *     --config=config/playwright.config.js
 *
 * Run with Workday credentials:
 *   WORKDAY_BASE_URL=https://impl.workday.com/capitaloneimpl1 \
 *   WORKDAY_USERNAME=finance.analyst@capitalone.com \
 *   WORKDAY_PASSWORD=<password> \
 *   npx playwright test workday-finance-regression.spec.js --headed
 */

const { test, expect } = require('../../fixtures');
const WorkdayFinancePage = require('../../pages/workday-finance.page');
const TD = require('../../data/workday-test-data');

// ─────────────────────────────────────────────────────────────────────────────
//  STORY: Finance Analyst creates and posts a balanced Journal Entry
//  Jira Ref: CAP-101
// ─────────────────────────────────────────────────────────────────────────────
test.describe('[UI] CAP-101: Workday Journal Entry — Create, Validate, and Post', {
  tag: ['@smoke', '@regression', '@workday', '@capital-one'],
}, () => {
  let finance;

  test.beforeEach(async ({ page }) => {
    finance = new WorkdayFinancePage(page);
    await finance.gotoCreateJournalEntry();
  });

  test('[C201] Test Case 1: Journal Entry form loads with Draft status', async ({ page }) => {
    // Assert — page loaded and form is in Draft state
    await expect(page).toHaveURL(TD.urlPatterns.journalEntry, { timeout: 15000 });
    await expect(page).toHaveTitle(TD.pageTitles.journalEntry, { timeout: 15000 });

    const status = await finance.getJournalEntryStatus();
    expect(status.trim()).toBe(TD.statuses.journalDraft);
  });

  test('[C202] Test Case 2: System rejects an out-of-balance journal entry', async ({ page }) => {
    const memo = `${TD.journalEntry.memoPrefix} CAP-101 TC2 ${Date.now()}`;

    // Arrange — add debit line only (no matching credit)
    await finance.setAccountingDate('04/20/2026');
    await finance.setMemo(memo);
    await finance.addJournalLine(
      TD.journalEntry.balancedDebit.ledgerAccount,
      TD.journalEntry.balancedDebit.amount,
      null,
      TD.journalEntry.balancedDebit.costCentre,
      0
    );

    // Act — attempt to post
    await finance.clickPost();

    // Assert — validation error shown
    const error = await finance.getValidationError();
    expect(error).toContain(TD.errors.outOfBalance);
  });

  test('[C203] Test Case 3: Successfully post a balanced journal entry', async ({ page }) => {
    const memo = `${TD.journalEntry.memoPrefix} CAP-101 TC3 ${Date.now()}`;

    // Arrange — balanced debit (5001) / credit (1000)
    await finance.setAccountingDate('04/20/2026');
    await finance.setMemo(memo);
    await finance.addJournalLine(
      TD.journalEntry.balancedDebit.ledgerAccount,
      TD.journalEntry.balancedDebit.amount,
      null,
      TD.journalEntry.balancedDebit.costCentre,
      0
    );
    await finance.addJournalLine(
      TD.journalEntry.balancedCredit.ledgerAccount,
      null,
      TD.journalEntry.balancedCredit.amount,
      TD.journalEntry.balancedCredit.costCentre,
      1
    );

    // Act
    await finance.clickPost();

    // Assert — status changed to Posted
    const status = await finance.getJournalEntryStatus();
    expect(status.trim()).toBe(TD.statuses.journalPosted);

    // Cleanup — reverse to keep sandbox clean
    await finance.clickReverse();
    const reversedStatus = await finance.getJournalEntryStatus();
    expect(reversedStatus.trim()).toBe(TD.statuses.journalReversed);
  });

  test('[C204] Test Case 4: Posted journal entry appears in GL Balance Report', async ({ page }) => {
    const memo = `${TD.journalEntry.memoPrefix} CAP-101 TC4 ${Date.now()}`;

    // Arrange — create and post balanced entry
    await finance.setAccountingDate('04/20/2026');
    await finance.setMemo(memo);
    await finance.addJournalLine(
      TD.journalEntry.balancedDebit.ledgerAccount,
      TD.journalEntry.balancedDebit.amount,
      null,
      TD.journalEntry.balancedDebit.costCentre,
      0
    );
    await finance.addJournalLine(
      TD.journalEntry.balancedCredit.ledgerAccount,
      null,
      TD.journalEntry.balancedCredit.amount,
      TD.journalEntry.balancedCredit.costCentre,
      1
    );
    await finance.clickPost();
    expect((await finance.getJournalEntryStatus()).trim()).toBe(TD.statuses.journalPosted);

    // Act — navigate to GL Balance Report
    await finance.gotoGLBalanceReport();
    await finance.runGLReport({
      glAccount: TD.journalEntry.balancedDebit.ledgerAccount,
      period: '2026-Q2',
    });

    // Assert — journal entry with this memo appears in the report
    const inReport = await finance.isTransactionInGLReport(memo);
    expect(inReport).toBe(true);

    // Cleanup
    await finance.gotoManageJournalEntries();
  });

  test('[C205] Test Case 5: Invalid GL account code shows correct error message', async ({ page }) => {
    // Arrange
    await finance.setAccountingDate('04/20/2026');
    await finance.addJournalLine(
      TD.journalEntry.invalidGlCode,
      TD.journalEntry.testAmount,
      null,
      TD.journalEntry.balancedDebit.costCentre,
      0
    );

    // Act — tab away to trigger validation
    await page.keyboard.press('Tab');

    // Assert
    const error = await finance.getInlineError();
    expect(error).toContain(TD.errors.invalidGlAccount);
  });

  test('[C206] Test Case 6: Accounting date in closed period is rejected', async ({ page }) => {
    // Arrange — use a known closed period date
    await finance.setAccountingDate(TD.journalEntry.closedPeriodDate);
    await finance.addJournalLine(
      TD.journalEntry.balancedDebit.ledgerAccount,
      TD.journalEntry.balancedDebit.amount,
      null,
      TD.journalEntry.balancedDebit.costCentre,
      0
    );
    await finance.addJournalLine(
      TD.journalEntry.balancedCredit.ledgerAccount,
      null,
      TD.journalEntry.balancedCredit.amount,
      TD.journalEntry.balancedCredit.costCentre,
      1
    );

    // Act
    await finance.clickPost();

    // Assert
    const error = await finance.getValidationError();
    expect(error).toContain(TD.errors.closedPeriod);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
//  STORY: Finance AP Analyst submits a Supplier Invoice
//  Jira Ref: CAP-102
// ─────────────────────────────────────────────────────────────────────────────
test.describe('[UI] CAP-102: Workday Supplier Invoice — Submit and Validate', {
  tag: ['@regression', '@workday', '@capital-one'],
}, () => {
  let finance;

  test.beforeEach(async ({ page }) => {
    finance = new WorkdayFinancePage(page);
    await finance.gotoCreateSupplierInvoice();
  });

  test('[C207] Test Case 7: Supplier Invoice form loads correctly', async ({ page }) => {
    await expect(page).toHaveURL(TD.urlPatterns.supplierInvoice, { timeout: 15000 });
    await expect(page).toHaveTitle(TD.pageTitles.supplierInvoice, { timeout: 15000 });
  });

  test('[C208] Test Case 8: Successfully submit a supplier invoice', async ({ page }) => {
    const uniqueInvoiceNumber = `INV-AAVA-${Date.now()}`;

    // Arrange
    await finance.fillSupplierInvoice({
      invoiceNumber: uniqueInvoiceNumber,
      supplier: TD.supplierInvoice.testSupplier,
      invoiceDate: '04/20/2026',
      amount: TD.supplierInvoice.testAmount,
    });

    // Act
    await finance.submitInvoice();

    // Assert
    const status = await finance.getInvoiceStatus();
    expect(status.trim()).toBe(TD.statuses.invoiceDraft);
  });

  test('[C209] Test Case 9: Duplicate invoice number triggers a warning', async ({ page }) => {
    // Arrange — attempt to use the same invoice number twice
    await finance.fillSupplierInvoice({
      invoiceNumber: TD.supplierInvoice.testInvoiceNumber,
      supplier: TD.supplierInvoice.testSupplier,
      invoiceDate: '04/20/2026',
      amount: TD.supplierInvoice.testAmount,
    });

    // Act
    await finance.submitInvoice();

    // Assert — duplicate warning appears
    const isDuplicateWarning = await finance.isDuplicateInvoiceWarningVisible();
    expect(isDuplicateWarning).toBe(true);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
//  STORY: Budget Owner views Budget vs Actual report
//  Jira Ref: CAP-103
// ─────────────────────────────────────────────────────────────────────────────
test.describe('[UI] CAP-103: Workday Budget vs Actual Report — View and Validate', {
  tag: ['@regression', '@workday', '@capital-one'],
}, () => {
  let finance;

  test.beforeEach(async ({ page }) => {
    finance = new WorkdayFinancePage(page);
    await finance.gotoBudgetVsActual();
  });

  test('[C210] Test Case 10: Budget vs Actual report page loads', async ({ page }) => {
    await expect(page).toHaveURL(TD.urlPatterns.budgetReport, { timeout: 15000 });
    await expect(page).toHaveTitle(TD.pageTitles.budgetReport, { timeout: 15000 });
  });

  test('[C211] Test Case 11: Report grid renders with data when filters are applied', async ({ page }) => {
    // Act — run report with Capital One Finance filters
    await finance.runBudgetVsActualReport({
      company: TD.budget.company,
      fiscalYear: TD.budget.fiscalYear,
      costCentre: TD.costCentres.corporateFinance,
    });

    // Assert — grid is visible and contains data
    const isGridVisible = await finance.isBudgetReportGridVisible();
    expect(isGridVisible).toBe(true);
  });

  test('[C212] Test Case 12: Variance column is present in Budget vs Actual report', async ({ page }) => {
    // Act
    await finance.runBudgetVsActualReport({
      company: TD.budget.company,
      fiscalYear: TD.budget.fiscalYear,
      costCentre: TD.costCentres.corporateFinance,
    });

    // Assert — variance column exists and has a value
    const varianceText = await finance.getBudgetVarianceText();
    expect(varianceText).toBeTruthy();
  });
});

// ─────────────────────────────────────────────────────────────────────────────
//  STORY: Payroll Manager views Payroll Results
//  Jira Ref: CAP-104
// ─────────────────────────────────────────────────────────────────────────────
test.describe('[UI] CAP-104: Workday Payroll Results — View Period Output', {
  tag: ['@regression', '@workday', '@capital-one'],
}, () => {
  let finance;

  test.beforeEach(async ({ page }) => {
    finance = new WorkdayFinancePage(page);
    await finance.gotoPayrollResults();
  });

  test('[C213] Test Case 13: Payroll Results page loads', async ({ page }) => {
    await expect(page).toHaveURL(TD.urlPatterns.payrollResults, { timeout: 15000 });
    await expect(page).toHaveTitle(TD.pageTitles.payrollResults, { timeout: 15000 });
  });

  test('[C214] Test Case 14: Payroll grid renders for current pay period', async ({ page }) => {
    // Act — run for the most recent pay period (Q1 2026)
    await finance.runPayrollResultsReport('Q1 2026');

    // Assert — grid is visible
    const isGridVisible = await finance.isPayrollGridVisible();
    expect(isGridVisible).toBe(true);
  });
});
